#!/bin/sh

libdir="/home/cpxx/Projects/mono-fuse-0.4.2/lib"
builddir="/home/cpxx/Projects/mono-fuse-0.4.2/example/RedirectFS"

DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}$libdir" \
LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$libdir" \
	mono --debug "$builddir/RedirectFS-FH.exe" "$@"

